[package]
name = "ray-tracing-codegen"
version = "0.1.0"
authors = ["stneng <web@stneng.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0"